# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresponse.proto\"\x1b\n\x0cNoneResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"S\n\rImageResponse\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x14\n\x0cnum_channels\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x03(\x02\"%\n\x15\x43onfigurationResponse\x12\x0c\n\x04json\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_NONERESPONSE']._serialized_start=18
  _globals['_NONERESPONSE']._serialized_end=45
  _globals['_IMAGERESPONSE']._serialized_start=47
  _globals['_IMAGERESPONSE']._serialized_end=130
  _globals['_CONFIGURATIONRESPONSE']._serialized_start=132
  _globals['_CONFIGURATIONRESPONSE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
